// <auto-generated />
using System;
using Fishing_API.Data.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Fishing_API.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Fishing_API.Models.BaitBrandModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BaitBrands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Signature Series"
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Supercast"
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Jumbo"
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Supercast"
                        },
                        new
                        {
                            Id = 5,
                            Brand = "Boulyn"
                        },
                        new
                        {
                            Id = 6,
                            Brand = "Fish"
                        },
                        new
                        {
                            Id = 7,
                            Brand = "Magic Baits"
                        },
                        new
                        {
                            Id = 8,
                            Brand = "Conoflex"
                        },
                        new
                        {
                            Id = 9,
                            Brand = "Trucella"
                        },
                        new
                        {
                            Id = 10,
                            Brand = "Self"
                        });
                });

            modelBuilder.Entity("Fishing_API.Models.BaitLogRelationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaitId")
                        .HasColumnType("integer");

                    b.Property<int>("LogId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaitId");

                    b.HasIndex("LogId");

                    b.ToTable("BaitLogRelations");
                });

            modelBuilder.Entity("Fishing_API.Models.BaitModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaitTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BaitTypeId");

                    b.HasIndex("BrandId");

                    b.ToTable("Baits");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaitTypeId = 7,
                            BrandId = 5,
                            Description = "Boulyn Kolletjie"
                        },
                        new
                        {
                            Id = 2,
                            BaitTypeId = 2,
                            BrandId = 2,
                            Description = "Perdeby"
                        },
                        new
                        {
                            Id = 3,
                            BaitTypeId = 2,
                            BrandId = 2,
                            Description = "Plain White"
                        },
                        new
                        {
                            Id = 4,
                            BaitTypeId = 2,
                            BrandId = 2,
                            Description = "Plain Yellow"
                        },
                        new
                        {
                            Id = 5,
                            BaitTypeId = 1,
                            BrandId = 2,
                            Description = "Pandemonium"
                        },
                        new
                        {
                            Id = 6,
                            BaitTypeId = 1,
                            BrandId = 2,
                            Description = "Fire and Ice"
                        },
                        new
                        {
                            Id = 7,
                            BaitTypeId = 1,
                            BrandId = 2,
                            Description = "Garlic"
                        },
                        new
                        {
                            Id = 8,
                            BaitTypeId = 1,
                            BrandId = 6,
                            Description = "Garlic"
                        },
                        new
                        {
                            Id = 9,
                            BaitTypeId = 1,
                            BrandId = 6,
                            Description = "Legend"
                        },
                        new
                        {
                            Id = 10,
                            BaitTypeId = 1,
                            BrandId = 6,
                            Description = "Sniper"
                        },
                        new
                        {
                            Id = 11,
                            BaitTypeId = 1,
                            BrandId = 6,
                            Description = "Banjo"
                        },
                        new
                        {
                            Id = 12,
                            BaitTypeId = 1,
                            BrandId = 3,
                            Description = "Banana"
                        },
                        new
                        {
                            Id = 13,
                            BaitTypeId = 1,
                            BrandId = 3,
                            Description = "Perdeby"
                        },
                        new
                        {
                            Id = 14,
                            BaitTypeId = 1,
                            BrandId = 7,
                            Description = "HLX"
                        },
                        new
                        {
                            Id = 15,
                            BaitTypeId = 1,
                            BrandId = 7,
                            Description = "Alm X"
                        },
                        new
                        {
                            Id = 16,
                            BaitTypeId = 2,
                            BrandId = 8,
                            Description = "Chop Chop"
                        },
                        new
                        {
                            Id = 17,
                            BaitTypeId = 1,
                            BrandId = 7,
                            Description = "Alm X"
                        },
                        new
                        {
                            Id = 18,
                            BaitTypeId = 1,
                            BrandId = 1,
                            Description = "Level 5"
                        },
                        new
                        {
                            Id = 19,
                            BaitTypeId = 1,
                            BrandId = 1,
                            Description = "SWG"
                        },
                        new
                        {
                            Id = 20,
                            BaitTypeId = 1,
                            BrandId = 1,
                            Description = "F2 Fifty"
                        },
                        new
                        {
                            Id = 21,
                            BaitTypeId = 1,
                            BrandId = 1,
                            Description = "Tjop Tjop"
                        },
                        new
                        {
                            Id = 22,
                            BaitTypeId = 1,
                            BrandId = 1,
                            Description = "DKW"
                        },
                        new
                        {
                            Id = 23,
                            BaitTypeId = 2,
                            BrandId = 1,
                            Description = "Banlick"
                        },
                        new
                        {
                            Id = 24,
                            BaitTypeId = 2,
                            BrandId = 1,
                            Description = "Garlic"
                        },
                        new
                        {
                            Id = 25,
                            BaitTypeId = 9,
                            BrandId = 1,
                            Description = "Level 5"
                        },
                        new
                        {
                            Id = 26,
                            BaitTypeId = 9,
                            BrandId = 6,
                            Description = "Perdeby"
                        },
                        new
                        {
                            Id = 27,
                            BaitTypeId = 8,
                            BrandId = 2,
                            Description = "Tutti Frutti"
                        },
                        new
                        {
                            Id = 28,
                            BaitTypeId = 8,
                            BrandId = 2,
                            Description = "Gumtree"
                        },
                        new
                        {
                            Id = 29,
                            BaitTypeId = 8,
                            BrandId = 2,
                            Description = "Vaaldam"
                        },
                        new
                        {
                            Id = 30,
                            BaitTypeId = 8,
                            BrandId = 2,
                            Description = "Caramel"
                        },
                        new
                        {
                            Id = 31,
                            BaitTypeId = 6,
                            BrandId = 6,
                            Description = "Honey High Attract Liquid"
                        },
                        new
                        {
                            Id = 32,
                            BaitTypeId = 6,
                            BrandId = 2,
                            Description = "Stinkvoete"
                        },
                        new
                        {
                            Id = 33,
                            BaitTypeId = 6,
                            BrandId = 2,
                            Description = "Schalas"
                        },
                        new
                        {
                            Id = 34,
                            BaitTypeId = 6,
                            BrandId = 2,
                            Description = "Honey Glow"
                        },
                        new
                        {
                            Id = 35,
                            BaitTypeId = 6,
                            BrandId = 2,
                            Description = "Schalas"
                        },
                        new
                        {
                            Id = 36,
                            BaitTypeId = 6,
                            BrandId = 2,
                            Description = "Tjop Tjop"
                        },
                        new
                        {
                            Id = 37,
                            BaitTypeId = 6,
                            BrandId = 2,
                            Description = "Almond S"
                        },
                        new
                        {
                            Id = 38,
                            BaitTypeId = 6,
                            BrandId = 2,
                            Description = "Kiana"
                        },
                        new
                        {
                            Id = 39,
                            BaitTypeId = 6,
                            BrandId = 2,
                            Description = "Gumtree"
                        },
                        new
                        {
                            Id = 40,
                            BaitTypeId = 6,
                            BrandId = 2,
                            Description = "Perdeby"
                        },
                        new
                        {
                            Id = 41,
                            BaitTypeId = 6,
                            BrandId = 2,
                            Description = "Banji"
                        },
                        new
                        {
                            Id = 42,
                            BaitTypeId = 6,
                            BrandId = 2,
                            Description = "Legend"
                        },
                        new
                        {
                            Id = 43,
                            BaitTypeId = 6,
                            BrandId = 2,
                            Description = "FX"
                        },
                        new
                        {
                            Id = 44,
                            BaitTypeId = 6,
                            BrandId = 9,
                            Description = "Hot Honey"
                        },
                        new
                        {
                            Id = 45,
                            BaitTypeId = 6,
                            BrandId = 1,
                            Description = "Turbo Garlic"
                        },
                        new
                        {
                            Id = 46,
                            BaitTypeId = 6,
                            BrandId = 1,
                            Description = "Juliass"
                        },
                        new
                        {
                            Id = 47,
                            BaitTypeId = 6,
                            BrandId = 1,
                            Description = "Plakker"
                        },
                        new
                        {
                            Id = 48,
                            BaitTypeId = 6,
                            BrandId = 1,
                            Description = "Agmed"
                        },
                        new
                        {
                            Id = 49,
                            BaitTypeId = 6,
                            BrandId = 1,
                            Description = "Hoekom Bloekom"
                        },
                        new
                        {
                            Id = 50,
                            BaitTypeId = 6,
                            BrandId = 1,
                            Description = "HKGK"
                        },
                        new
                        {
                            Id = 51,
                            BaitTypeId = 6,
                            BrandId = 1,
                            Description = "Raptor"
                        },
                        new
                        {
                            Id = 52,
                            BaitTypeId = 11,
                            BrandId = 1,
                            Description = "Level 5 Feedmix"
                        },
                        new
                        {
                            Id = 53,
                            BaitTypeId = 12,
                            BrandId = 10,
                            Description = "African Night Crawlers"
                        });
                });

            modelBuilder.Entity("Fishing_API.Models.BaitTypeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BaitTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Oozing Floatie"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Hard Floatie"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Fluke"
                        },
                        new
                        {
                            Id = 4,
                            Type = "Trick Worm"
                        },
                        new
                        {
                            Id = 5,
                            Type = "Crank Bait"
                        },
                        new
                        {
                            Id = 6,
                            Type = "Dip"
                        },
                        new
                        {
                            Id = 7,
                            Type = "Ground Feed"
                        },
                        new
                        {
                            Id = 8,
                            Type = "Mielies"
                        },
                        new
                        {
                            Id = 9,
                            Type = "Bullets"
                        },
                        new
                        {
                            Id = 10,
                            Type = "Dough"
                        },
                        new
                        {
                            Id = 11,
                            Type = "Feed Mix"
                        },
                        new
                        {
                            Id = 12,
                            Type = "Live"
                        });
                });

            modelBuilder.Entity("Fishing_API.Models.DamLocationModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DamId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DamId");

                    b.ToTable("DamLocations");
                });

            modelBuilder.Entity("Fishing_API.Models.DamModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Dam");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rietvlei",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aston Lake",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wonderland45",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Struben Dam",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Roodeplaat",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Rietvlei",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 7,
                            Name = "Bronkhorstspruit Nature Reserve",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "Bajadam",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 9,
                            Name = "Rapids Paradise",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 10,
                            Name = "Oranjeville",
                            ProvinceId = 5
                        },
                        new
                        {
                            Id = 11,
                            Name = "Vaal Marina",
                            ProvinceId = 5
                        });
                });

            modelBuilder.Entity("Fishing_API.Models.FishSpeciesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FishSpecie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FishSpecies");
                });

            modelBuilder.Entity("Fishing_API.Models.LogModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DamLocationId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Day")
                        .HasColumnType("date");

                    b.Property<int>("FishSpecieId")
                        .HasColumnType("integer");

                    b.Property<int>("RigsId")
                        .HasColumnType("integer");

                    b.Property<int>("Temperature")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("Time")
                        .HasColumnType("time without time zone");

                    b.Property<int>("WeatherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DamLocationId");

                    b.HasIndex("FishSpecieId");

                    b.HasIndex("RigsId");

                    b.HasIndex("WeatherId");

                    b.ToTable("LogModels");
                });

            modelBuilder.Entity("Fishing_API.Models.ProvinceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProvinceName = "Gauteng"
                        },
                        new
                        {
                            Id = 2,
                            ProvinceName = "Limpopo"
                        },
                        new
                        {
                            Id = 3,
                            ProvinceName = "North-West"
                        },
                        new
                        {
                            Id = 4,
                            ProvinceName = "Mpumalanga"
                        },
                        new
                        {
                            Id = 5,
                            ProvinceName = "Free State"
                        },
                        new
                        {
                            Id = 6,
                            ProvinceName = "Kwazulu Natal"
                        },
                        new
                        {
                            Id = 7,
                            ProvinceName = "Northern Cape"
                        },
                        new
                        {
                            Id = 8,
                            ProvinceName = "Western Cape"
                        },
                        new
                        {
                            Id = 9,
                            ProvinceName = "Eastern Cape"
                        });
                });

            modelBuilder.Entity("Fishing_API.Models.RigsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RigName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rigs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RigName = "Sliding Rietvlei"
                        },
                        new
                        {
                            Id = 2,
                            RigName = "Sliding Rietvlei Single Hook"
                        },
                        new
                        {
                            Id = 3,
                            RigName = "Weedless Texas"
                        },
                        new
                        {
                            Id = 4,
                            RigName = "None"
                        });
                });

            modelBuilder.Entity("Fishing_API.Models.WeatherModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Weather")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Weather");
                });

            modelBuilder.Entity("Fishing_API.Models.BaitLogRelationModel", b =>
                {
                    b.HasOne("Fishing_API.Models.BaitModel", "Bait")
                        .WithMany()
                        .HasForeignKey("BaitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fishing_API.Models.LogModel", "Log")
                        .WithMany()
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bait");

                    b.Navigation("Log");
                });

            modelBuilder.Entity("Fishing_API.Models.BaitModel", b =>
                {
                    b.HasOne("Fishing_API.Models.BaitTypeModel", "BaitType")
                        .WithMany()
                        .HasForeignKey("BaitTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fishing_API.Models.BaitBrandModel", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaitType");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Fishing_API.Models.DamLocationModel", b =>
                {
                    b.HasOne("Fishing_API.Models.DamModel", "Dam")
                        .WithMany()
                        .HasForeignKey("DamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dam");
                });

            modelBuilder.Entity("Fishing_API.Models.DamModel", b =>
                {
                    b.HasOne("Fishing_API.Models.ProvinceModel", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });

            modelBuilder.Entity("Fishing_API.Models.LogModel", b =>
                {
                    b.HasOne("Fishing_API.Models.DamLocationModel", "DamLocation")
                        .WithMany()
                        .HasForeignKey("DamLocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fishing_API.Models.FishSpeciesModel", "FishSpecie")
                        .WithMany()
                        .HasForeignKey("FishSpecieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fishing_API.Models.RigsModel", "Rigs")
                        .WithMany()
                        .HasForeignKey("RigsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fishing_API.Models.WeatherModel", "Weather")
                        .WithMany()
                        .HasForeignKey("WeatherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DamLocation");

                    b.Navigation("FishSpecie");

                    b.Navigation("Rigs");

                    b.Navigation("Weather");
                });
#pragma warning restore 612, 618
        }
    }
}
